project:
  type: website
  output-dir: docs

website:
  title: "Mini-course CoDA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com
  sidebar:
    style: "docked"
    search: true
    contents:
      - 1_intro.qmd
      - 2_principle.qmd
  page-navigation: true

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

