---
title: "Mini-course compositional data analysis 2024"
tbl-colwidths: [20, 60, 20]
---

Date: **Jan 9-10 2024**

Room: **Location TBA**

Instructors: Christian L. Müller, Stefanie Peschel, Viet Tran

------------------------------------------------------------------------

<!-- ::: callout-note -->

<!-- ## This workshop template -->

<!-- This workshop template contains 4 pages: -->

<!-- -   Home: `index.qmd` (this page) -->

<!-- -   About: `about.qmd` -->

<!-- Two content pages -->

<!-- -   Page without code: `part_1_prep.qmd` -->

<!-- -   Page with R code: `part_2_eda.qmd` -->

<!-- It is straightforward to add more content pages: you need to create a new `.qmd` file (or copy/paste the existing ones), then link the new page inside `_quarto.yml`. -->

<!-- ::: -->

<!-- ::: callout-tip -->

<!-- ## Homepage of your workshop -->

<!-- This is the **homepage** `index.qmd` for your workshop, so ideally it should contain some key information such as **time and place, instructors** and information of the course/workshop. -->

<!-- It should be easy to navigate. -->

<!-- ::: -->

# Welcome!

-   The goal of the workshop is to help participants understand and apply concepts of compositional data analysis
-   Workshop material can be found in the workshop github repository (TBA).

#### Learning Objectives

At the end of the course, participants will be able to

-   understand key concepts of compositional data analysis
-   apply concepts of compositional data analysis in R

#### Pre-requisites

-   Basic familiarity with R (e.g., [tutorial R for ecology](https://datacarpentry.org/R-ecology-lesson/index.html))

# Schedule

Tuesday

| Time             | Topic                                                                   | Presenter          |
|:-----------------|:------------------------------------|:-----------------|
| 9:00 - 10:00     | Session 1: Intro to compositional sequencing data                       | Instructor CLM     |
| 10:15 - 11:00    | Presentation of student data (fast track)                               | all                |
| 11:15 - 12:00    | Session 2: Principles of compositional data                             | Instructor CLM     |
| 12:00 - 13:00    | Lunch break                                                             | all                |
| 13:00 - 14:00    | Session 3: Exploratory analysis of compositional data in R (part I)     | Instructor CLM, VT  |
| 14:15 - 15:15    | [Session 4: Exploratory analysis of compositional data in R (part II)](4_eda.qmd) | Instructor CLM, SP     |
| 15:15 - 15:45    | Fika                                                                    | all                |
| 15:45 - 17:00    | Session 5: Differential abundance testing and regression                | Instructor CLM, VT |
| 17:00 - open end | Application to own data                                                 | all                |

Wednesday

| Time             | Topic                                                                         | Presenter          |
|:-----------------|:------------------------------------|:-----------------|
|  9:00 - 09:30    | Recap and open issues                                                         | Instructor CLM     |
|  9:45 - 10:45    | Session 6: Regression analysis for compositional data                         | Instructor CLM, VT |
| 11:00 - 12:00    | [Session 7: Estimating microbial association networks](slides/07-Microbial_association_networks.pdf)                                                   | Instructor CLM, SP |
| 12:00 - 13:00    | Lunch break                                                                   | all                |
| 13:00 - 13:30    | [Session 8: Practical applications of learned concepts in R (regression)](9_practical.qmd) | Instructor SP, VT  |
| 13:30 - 14:00    | [Session 8: Practical applications of learned concepts in R (networks)](8_practical_networks.qmd) | Instructor SP, VT  |
| 14:15 - 15:15    | Session 9: Time series analysis for compositional data                        | Instructor CLM     |
| 15:15 - 15:45    | Fika                                                                          | all                |
| 15:45 - 16:15    | Session 10: Recap and further topics                                          | Instructor CLM     |
| 16:15 - open end | Application to own data                                                       | all                |

# Additional material

-   [Construct the soil phyloseq object](90_soil_phyloseq.qmd)

Website created with the [qtwAcademic template](https://github.com/andreaczhang/qtwAcademic) based on quarto.
